### PR TITLE
derive: implement #[valuable] attributes

### PR DESCRIPTION
**Pull request by taiki-e**
The first step for #51.

- `#[valuable(rename = "...")]`
- `#[valuable(transparent)]`
- `#[valuable(skip)]`

~~(This commit was created about 5 months ago. However, I didn't open the PR at the time because something was missing, but I don't remember what it is anymore, so I'll open the PR as a draft anyway.)~~

### CODE REVIEW

**Comment by rwestphal** [comment]
Would love to see this getting added!

**Comment by fosskers** [comment]
Any news on this?

**Comment by johnhurt** [comment]
Hey, I'm not sure why this pr stalled out, but I really like the functionality and the way you've written it. I am going to try to push it forward. I added a new pr that duplicates the work you did here (and rightly attributes authorship to you). My pr also includes a macro attribute for formatting a field for including a simplified version of a field when the field's type doesn't implement `Valuable`. Thanks for your work here! I hope we can get it included in the actual codebase.

**Review by carllerche — APPROVED** [review]
This looks fine to me, feel free to merge.

**Pull request merged**
